Name:           perl-RDF-Trine
Version:        0.138
Release:        1%{?dist}
Summary:        RDF Framework for Perl
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/RDF-Trine/
Source0:        http://www.cpan.org/modules/by-module/RDF/RDF-Trine-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch

BuildRequires:  perl >= 1:5.8.3
BuildRequires:  perl(Algorithm::Combinatorics)
BuildRequires:  perl(Data::UUID)
BuildRequires:  perl(DBD::SQLite) >= 1.14
BuildRequires:  perl(DBI)
BuildRequires:  perl(DBIx::Connector)
BuildRequires:  perl(Digest::SHA)
BuildRequires:  perl(Error)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(HTTP::Negotiate)
BuildRequires:  perl(JSON) >= 2
BuildRequires:  perl(List::Util)
BuildRequires:  perl(Log::Log4perl)
BuildRequires:  perl(LWP::UserAgent)
BuildRequires:  perl(Module::Load::Conditional) >= 0.38
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Set::Scalar)
BuildRequires:  perl(Test::Exception)
BuildRequires:  perl(Test::JSON)
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(Text::CSV)
BuildRequires:  perl(Text::Table)
BuildRequires:  perl(URI) >= 1.52
BuildRequires:  perl(XML::CommonNS) >= 0.04
BuildRequires:  perl(XML::LibXML) >= 1.7
BuildRequires:  perl(XML::Namespace)
BuildRequires:  perl(XML::SAX) >= 0.96
Requires:       perl(Algorithm::Combinatorics)
Requires:       perl(Data::UUID)
Requires:       perl(DBD::SQLite) >= 1.14
Requires:       perl(DBI)
Requires:       perl(DBIx::Connector)
Requires:       perl(Digest::SHA)
Requires:       perl(Error)
Requires:       perl(HTTP::Negotiate)
Requires:       perl(JSON) >= 2
Requires:       perl(List::Util)
Requires:       perl(Log::Log4perl)
Requires:       perl(LWP::UserAgent)
Requires:       perl(Module::Load::Conditional) >= 0.38
Requires:       perl(Scalar::Util)
Requires:       perl(Set::Scalar)
Requires:       perl(Text::CSV)
Requires:       perl(Text::Table)
Requires:       perl(URI) >= 1.52
Requires:       perl(XML::CommonNS) >= 0.04
Requires:       perl(XML::LibXML) >= 1.7
Requires:       perl(XML::Namespace)
Requires:       perl(XML::SAX) >= 0.96
Requires:       perl(Redis)
Requires:       perl(Cache::LRU)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
RDF::Trine provides an RDF framework with an emphasis on extensibility, API
stability, and the presence of a test suite. The package consists of
several components:

%prep
%setup -q -n RDF-Trine-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes.ttl README
%{perl_vendorlib}/*
%{_mandir}/man3/*
%{_bindir}/srx2csv
%{_bindir}/srx2table

%changelog
* Sun Feb 12 2012 Pierre-Yves Chibon 0.138-1
- Specfile autogenerated by cpanspec 1.78.
