Name:           perl-XML-NamespaceFactory
Version:        1.00
Release:        1%{?dist}
Summary:        Simple factory objects for SAX namespaced names
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/XML-NamespaceFactory/
Source0:        http://www.cpan.org/modules/by-module/XML/XML-NamespaceFactory-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Simply create a new XML::NamespaceFactory object with the namespace you
wish to use as its single parameter. If you wish to use the empty
namespace, simply pass in an empty string (but undef will not do).

%prep
%setup -q -n XML-NamespaceFactory-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun Feb 12 2012 Pierre-Yves Chibon 1.00-1
- Specfile autogenerated by cpanspec 1.78.
